import { config } from 'dotenv';

config();

const env = process.env;

export default {
  GROQ_API_KEY: env.GROQ_API_KEY!,
  GEMINI_API_KEY: env.GEMINI_API_KEY!,

  NEXT_PUBLIC_FIREBASE_API_KEY: env.NEXT_PUBLIC_FIREBASE_API_KEY!,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET!,
  NEXT_PUBLIC_FIREBASE_MESSANGER_ID: env.NEXT_PUBLIC_FIREBASE_MESSANGER_ID!,
  NEXT_PUBLIC_FIREBASE_APP_ID: env.NEXT_PUBLIC_FIREBASE_APP_ID!,

  FIREBASE_CLIENT_MAIL: env.FIREBASE_CLIENT_MAIL!,
  FIREBASE_PRIVATE_KEY: env.FIREBASE_PRIVATE_KEY!,

  NEXT_PUBLIC_TWONTWOD_ENDPOINT: env.NEXT_PUBLIC_TWONTWOD_ENDPOINT!,

  DATABASE_URL: env.DATABASE_URL!,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  NEXT_PUBLIC_SUPABASE_URL: env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_SERVICE_KEY: env.SUPABASE_SERVICE_KEY!,

  R2_BUCKET_NAME: env.R2_BUCKET_NAME!,
  R2_BUCKET_ENDPOINT: env.R2_BUCKET_ENDPOINT!,
  R2_ACCESS_KEY_ID: env.R2_ACCESS_KEY_ID!,
  R2_SECRET_ACCESS_KEY: env.R2_SECRET_ACCESS_KEY!,
  R2_BUCKET_PUBLIC_ENDPOINT: env.R2_BUCKET_PUBLIC_ENDPOINT!
};
